### ISSUE TITLE
Massive Performance Issue in Firefox

### ISSUE THREAD

**Issue by emkayy** [eqcss/eqcss#9] opened 2016-03-02 18:43 UTC
The site http://elementqueries.com/ is almost unusable due to performance problems.
Scrolling has a huge delay.
It's a nice concept, but I wouldn't use it in production!

**Comment by tomhodgins** [comment] 2016-03-02 19:14
Hi emkayy! Thanks for your interest, we've been using this in production for months now and there haven't experienced performance issues in Firefox until this morning, when I got a tweet this same issue.

I can reproduce it in FF 44 here as well, has something about Firefox changed recently?

I believe this is happening because Firefox is recalculating the styles too enthusiastically on scroll. I'm going to test the nightly versions of Firefox now to see if they've resolved what's going on already.

I've just investigated this in today's [Firefox nightly build](https://nightly.mozilla.org/) and it's _smooth as butter_, so I don't know why it broke, or what versions other than FF44 and FF46 that are affected, but it seems Mozilla has already fixed it upstream and we just have to wait for this broken build to update to a new version soon. Actually, you should test it out in Firefox Nightly, it's _really_ fast there!! (min says it's FF47)

In the meantime while we wait for firefox to update, EQCSS still works great in IE8 (and every other browser) if you want to play around with it!

**Comment by suprsidr** [comment] 2016-03-02 20:17
> I believe this is happening because Firefox is recalculating the styles too enthusiastically on scroll.

Debounce it man!

**Comment by suprsidr** [comment] 2016-03-04 21:28
https://hacks.mozilla.org/2016/02/smoother-scrolling-in-firefox-46-with-apz/

**Comment by WilliamVercken** [comment] 2016-06-09 07:46
I tested on firefox 47 (windows 10), and I have issues too on scrolling.

**Comment by tomhodgins** [comment] 2016-06-09 18:53
We're still thinking about how best to implement this, and I'm hoping we can have something in place within the next week 👍

**Comment by tomhodgins** [comment] 2016-06-14 03:16
Aw yeah, check this out @emkayy & @WilliamVercken! Here's what we came up with after thought & testing: https://github.com/eqcss/eqcss/releases/tag/v1.2.0

It's been updated in NPM, so it should be available on cdnJS shortly!

Let me know if this fixes your problem :)

**Comment by tomhodgins** [comment] 2016-06-17 13:28
After testing I'm going to go ahead and close this one now! Everything's looking smooth as butter :)

**Closed as completed by tomhodgins** 2016-06-17 13:28 UTC

**Comment by smajl** [comment] 2016-07-11 11:56
@tomhodgins Demo site http://elementqueries.com/ (currently with 1.2.1), FIrefox 47.0.1, Windows 8.1. Huge lags when scrolling inside elements, sorry. This seems not resolved to me. :( Can I provide some other environment info?

EDIT: Tested on another machine running Windows and Firefox. Lag confirmed.
EDIT2: Seems like everything lags: scrolling the page or elements, typing, resizing, adding elements, etc. Really unusable.

**Comment by DavidOliver** [comment] 2016-08-26 15:43
The demo page performance is not good for me in Firefox 48, Ubuntu, on a fairly beefy machine. There seems to be a very noticeable pause every half a second or so when scrolling or interacting with elements.

Very interesting project, by the way. I hope to try it out soon. Thanks!

**Comment by myfonj** [comment] 2016-08-26 16:14
Firefox generally suffers while getting ANY style updates, even when `<style>` element content value "changes" to the same as before. I proposed some optimisations for fixing this issue in https://github.com/eqcss/eqcss/pull/22/files …
