### ISSUE TITLE
Can you instantiate the keyword selectors?

### ISSUE THREAD

**Issue by dropddesigns** [eqcss/eqcss#12] opened 2016-05-04 00:27 UTC
I'm using a modified version of the BEM syntax and was wondering if you can instantiate $this with a modifier

e.g.

@element '.block' and (min-width: 300px) {
  $this {
    background-color: #000;
  }

  $[this]--brighten {
    background-color: #FFF;
  }
}

**Comment by tomhodgins** [comment] 2016-05-04 01:19
Hi Drop D! Thanks for playing around with EQCSS :)

What's actually going on with `$this` is that it refers not just to elements matching the `.block` selector, but when the page loads the plugin is assigning each `.block` it finds on the page its own unique identifier. Imagine this is our HTML:

```
<body>
  <header>
    <div></div>
  </header>
  <main>
    <section>
      <div></div>
    </section>
    <aside>
      <div></div>
    </aside>
  </main>
</body>
```

And our styles looked like this:

```
@element 'div' {
  $this {
    background: red;
  }
}
```

What's really going to happen is something like this when the page loads. It finds each element on the page that matches the query, and tags them with an identified, then outputs styles based on those identifiers:

```
<body>
  <header>
    <div data-eqcss-1></div>
  </header>
  <main>
    <section>
      <div data-eqcss-2></div>
    </section>
    <aside>
      <div data-eqcss-3></div>
    </aside>
  </main>
  <style>
    [data-eqcss-1] {
      background: red;
    }
    [data-eqcss-2] {
      background: red;
    }
    [data-eqcss-3] {
      background: red;
    }
  </style>
</body>
```

Now in this example there's no responsive query, so all three of our `div` elements get the style all the time, but imagine these three `div` elements are different widths on the page at any given moment and they have a query like this:

```
@element 'div' and (min-width: 300px) {
  $this {
    background: red;
  }
}
```

Now let's say the whole browser is 200px wide, no matter what, all three of those `div` elements are going to have the style applied like our last example because they'd all be showing up squished below 300px wide no matter what. But suppose the browser is 1000px wide, and only the `div` in the sidebar finds itself below 300px wide, this is what the page would look like:

```
<body>
  <header>
    <div data-eqcss-1></div>
  </header>
  <main>
    <section>
      <div data-eqcss-2></div>
    </section>
    <aside>
      <div data-eqcss-3></div>
    </aside>
  </main>
  <style>
    [data-eqcss-1] {
    }
    [data-eqcss-2] {
    }
    [data-eqcss-3] {
      background: red;
    }
  </style>
</body>
```

So, with this explanation of how `$this` works we can figure out how to use it better with BEM classes. Supposing you have HTML like this:

```
<div class="block">Block</div>
<div class="block--brighten">Brightened Block</div>
```

We will need to use attribute selectors to target this, but we _can_ come up with something that works like how you want `$[this]--brighten` to function. Instead of selecting the elements with a class of `block` with the dot notation for classes, let's use an attribute selector to find all elements whose classes start with `block`: `[class^="block"]`.

Then, inside our query (now for `[class^=block]`) we can select all elements whose classes end in `--brighten` by again using an attribute selector, `[class$="--brighten"]`. The `$` means 'ends with', but if you had a class with formatting like `first--second--third` you could target the middle word with `*` which just searches for that string anywhere in the attribute value like `[class*="--second--"]`.

So in order to find all `.block--brighten` elements with `$this`, and `$this` is already referring to a data-attribute, than we can just gang-up the two attribute selectors. In theory the code output to the page will end up looking like `[data-EQCSS-1][class$="--brighten"]`

```
<style>
  @element '[class^=block]' and (min-width: 300px) {
    $this {
      background: red;
    }
    $this[class*="--brighten"] {
      background: lightpink;
    }
  }
</style>
```

You can read more about the details of how the plugin actually applies the styles to the page here: http://elementqueries.com/notes/technical-documentation.html

Hope this helps! Happy hacking :)

**Comment by dropddesigns** [comment] 2016-05-04 04:24
Hi Tommy,

Thank you so much for the quick response plus taking the time to explain how that all hangs together.

Managed to take your example and get that working with the attribute selectors.

Just some additional feedback (which may be due to my implementation) is that I am having trouble using ems in my CSS but using pixels works fine.

You can download the HTML in the following gist to see what I am trying to achieve. Just need to change the viewport width: https://gist.github.com/dropddesigns/7fa38bb862331c658d40b2e986b6e6da

The problem is that if I use ems (or maybe even percentage), the element queries don't seem to kick in at the narrower viewports. Hopefully I haven't introduced some cyclic redundancy.

I noticed your 'Button styles' example on the following page has something similar to what I have in my mind but the source seems to be in pixels too:
http://elementqueries.com/demos/content-blocks.html

Kindest regards,

Beau

**Comment by tomhodgins** [comment] 2016-06-15 22:16
Hey @dropddesigns! Thanks for your patience, I've played around with the demo again and I think I have something working now: http://codepen.io/tomhodgins/pen/ezzWxN

**Comment by dropddesigns** [comment] 2016-06-15 22:57
I'm not sure I'm seeing the 'layout' columns and even the style of the flag object changing at the different breakpoints. It does look like the 'layout' changes slightly at one breakpoint to go to a mobile view but the flag object just scales, rather than changes.

To get an idea of what I was going for, please see the image to give you the rough breakpoint breakdown as well as the expected change to the flag object. My Gist should demonstrate this if you use pixels...

I updated the gist locally and added the max-width ems in the media queries but that didn't seem to work the same way as the pixels were working.

Note: I also noticed the @element query was set to 600em but it should be 37.5em (600px) assuming you are just converting what I originally had. Not sure if that has any baring either

![breakpoints](https://cloud.githubusercontent.com/assets/2650467/16100182/440be610-338f-11e6-874a-f26652f8a5eb.jpg)

**Comment by tomhodgins** [comment] 2016-06-15 23:07
Ah! I see what you’re trying to build. I’m going to mock up a version from scratch with less HTML and styles so you can see how this would work. I think you’re trying to do too much :)

You really have one layout with three responsive behaviours:
- any time the article is wide enough, it should float the image to the left
- when the container is wide enough, the first article is given a special style
- when the container is wide enough, all but the first should be half-width

Let me see what I can come up with!

**Comment by tomhodgins** [comment] 2016-06-15 23:30
Success! I've recreated a demo with the functionality from your screenshots, using EMs :)

Video: https://www.youtube.com/watch?v=u5NpmD5WMsY

Codepen demo: http://codepen.io/tomhodgins/pen/jrrwmP

…and I've attached a standalone HTML test that has everything you need in it! Take it easy :D

[dd-demo.html.zip](https://github.com/eqcss/eqcss/files/317380/dd-demo.html.zip)

Does this solve the issue?

**Comment by dropddesigns** [comment] 2016-06-15 23:30
It is actually a little different to those responsive behaviours you described.

I've kind of got two separate examples on the page with various behaviours
1. A single column layout with one flag object (or article)
2. A two column layout with one flag object (or article) in each column

---
1. At around 800px, the image in this flag should get bigger to accommodate for the fact that the height of the paragraphs will increase due to a narrower viewport

2a. At a narrow viewport (~ 380px), stack the flag objects' elements
2b. At a narrow viewport (between 380 and 600px), stack the columns of the two column layout. Don't stack the flag objects' elements
2c. At a wider viewport (between 600px and ~ 830px), stack the flag objects' elements
2d. At a wide viewport (> 830px), display the flag object as usual (image and text side by side)
2e. At super wide width, make the image in the flag object a fixed size to suit the short paragraph at a wide viewport

**Comment by dropddesigns** [comment] 2016-06-15 23:31
Let me check out what you've got as it may still satisfy the updated behaviours I described.

You came back to me before I managed to type it all out :)

PS I do typically try to do too much haha

**Comment by tomhodgins** [comment] 2016-06-15 23:38
You're still thinking viewport-first, not element-first. Imagine when you're writing `@element` queries that the element in the query is the viewport for a moment, you're making that element self-responsive, it doesn't really matter how wide the browser is.

If you load these self-responsive article elements into a container that also has columns when there's room for it - you don't have to keep thinking about the widths where you need to switch the articles from stacked, to side-by-side, back to stacked, and back to side-by-side… their own width-based queries will figure out their own layout out wherever you stick 'em :)

I've written this already which might help explain that change in approach, and there are more articles coming soon: http://elementqueries.com/notes/its-time-to-think-element-first.html

**Comment by dropddesigns** [comment] 2016-06-16 04:17
I have made some tweaks to set it up as intended.

An article outside of a grid layout.

Articles inside of a two column grid layout.

The elements within an article should be stacked based on the width of the article.

The grid columns should be stacked based on the width of the container (.columns).

This should be more in line with the element-first way of thinking.

Please have a look below because you will see at line 113, I am still having to use pixels to get the display to change in the browser.

I feel that this is a realistic example, especially in a modular/content management system arena when we have a content type, placed within a layout and both the content type and layout must change.

[dd-demo-updated.zip](https://github.com/eqcss/eqcss/files/317669/dd-demo-updated.zip)

**Comment by tomhodgins** [comment] 2016-06-16 04:29
I'm not sure where your demo is going wrong here, but I updated my demo and it's still working with `(min-width: 37em)`:
- Moved the first `article` outside the `section`
- Removed special `:first-of-type` styling
- Switched `:nth-of-type(odd)` to `:nth-of-type(even)` because there's no special first item anymore

And it's still using an `em`-based breakpoint. I'm just not sure why it's not working for you or what you're trying to do here that isn't what I'm doing :S Is my demo doing what you want now?

Here's my updated demo with the first `article` pulled outside so it never gets put into columns. No need to wrap it as it's already self-responsive, and also no need for wrappers around the two columns either. We can keep the exact same number of elements as my first demo and just cut down on the CSS, we don't even need to add anything new!

Updated demo: http://codepen.io/tomhodgins/pen/dXXVXX

**Comment by dropddesigns** [comment] 2016-06-16 21:41
Firstly, thank you for your quick responses and the level of detail you are going to (YouTube, codepens, HTML demos). Hopefully I can help you by you helping me ;)

Note: taken my last few tweets to you and repackaged it to continue the conversation here...

My premise is that we don’t control article widths (eg 33%, 50%, 100%) because we may not know where the article will exist or how wide it will be.

I see this being based on the layout (or grid) that you are using for a page.

The articles could be nested a couple of layers deep. The idea is that the article gets inserted anywhere and its child elements 'adapt' and are styled accordingly to the width of the article.

Maybe element queries are different to container queries and I’m mixing the two concepts?

After looking at the demo, I think our approaches are still different.

I think the resulting output in terms of how the articles are changing and scaling and responding is the same, but the implementation is not.

I've created an image to illustrate where I am coming from. The three areas surrounded by the dashed borders indicate three different components (could be portlets, different modules, different source APIs etc).

The articles represented in the three different components are the same article.

The idea is that the article content comes back with the exact same classes and basic HTML structure each time. We don't necessarily have the control to add more classes.

Therefore, we set element queries on the article to say if the article is under a certain width, stack the image and body copy (we can achieve this).

However, if the article is inside a two, three, four column grid layout, we also want the columns to change their width (25%, 33%, 50%, 100%) depending on the width of the grid container.

Note: this could be where I'm going wrong, maybe I don't use element queries here. Maybe I use container queries (assuming they're different) or base this on the viewport width instead.

To make it more complex though, the grid may be nested so you probably can't rely solely on the browser viewport width. Ultimately, this is why we need element/container queries in the first place right?

The important part is that the article changes based on its size but it could be situated by itself in a section spanning 100%, it could be in a multi column grid layout, an article in each column cell or it could even be sitting in a narrow aside.

What I've found is that when the article has an element query, placing it inside another component that also has an element query, you have to use pixels as the relative units don't seem to work.

![layouts](https://cloud.githubusercontent.com/assets/2650467/16134085/d33681d8-344d-11e6-8861-ca63613dc7ae.jpg)

**Comment by tomhodgins** [comment] 2016-06-16 23:08
> My premise is that we don’t control article widths (eg 33%, 50%, 100%) because we may not know where the article will exist or how wide it will be.
> 
> The articles could be nested a couple of layers deep. The idea is that the article gets inserted anywhere and its child elements 'adapt' and are styled accordingly to the width of the article.

Yes, this is the idea behind EQCSS. I see this being based on the layout (or grid) that you are using for a page.

> Maybe element queries are different to container queries and I’m mixing the two concepts?

No, you aren't mixing them up. There _can_ be a difference but in this case EQCSS is a container-style element query syntax, just like how `@media` queries are a container that wrap a block of styles. Some people support element queries just on individual elements themselves at the rule level, so you wouldn't be able to affect any element on the page other than the one meeting the condition. Our container-style approach lets you style any element on the page when a condition is met :)

Here's a pseudo-code rule-level element query, it couldn't style anything other than itself

```
.widget[width<300px] {
  color: red;
}
```

Versus a container-style query, which can style itself, child elements, but also any element on the page:

```
@container '.widget' (width<300px) {

  .widget {
    color: red;
  }
  .widget a {
    color: blue;
  }
  .widget-wrapper {
    border: 1px solid black;
  }

}
```

Both of the syntaxes in this are fictional, but should illustrate the difference. Container query isn't synonmous with element query, because isn't `@media` a container query already? I'm not sure if there's a convenient term for the attribute-style element query approach, the non-container-style element query plugins.

> I've created an image to illustrate where I am coming from. The three areas surrounded by the dashed borders indicate three different components (could be portlets, different modules, different source APIs etc).
> The articles represented in the three different components are the same article.
> The idea is that the article content comes back with the exact same classes and basic HTML structure each time. We don't necessarily have the control to add more classes.
> Therefore, we set element queries on the article to say if the article is under a certain width, stack the image and body copy (we can achieve this).

Yes, this is exactly the use case behind the development of Element Queries. I made some [nice responsive tables](http://staticresource.com/tables), but then when we started putting them in layouts with sidebars, and at different sizes, suddenly all my break-points were off. So instead of writing viewport-relative responsive queries I can just style on element from 200px up to 2000px and I never have to worry about where it gets displayed, I know it will adapt to look its best.

Here's a video of me converting a `@media`-based navigation into `@element` queries that shows that once you have it in `@element` queries you can stick it in any size of container and it will adapt: https://www.youtube.com/watch?v=ybCrzsglqXM

> However, if the article is inside a two, three, four column grid layout, we also want the columns to change their width (25%, 33%, 50%, 100%) depending on the width of the grid container.
> 
> To make it more complex though, the grid may be nested so you probably can't rely solely on the browser viewport width. Ultimately, this is why we need element/container queries in the first place right?

You can't nest `@element` queries inside each other, but you can nest elements with `@element` queries applied inside each other just fine. Check out [this demo](http://staticresource.com/widget-demo.html) for a lightweight example, and [this demo](http://staticresource.com/squeezeCSS/) for probably the heaviest, most convoluted nested example of EQCSS that's been built so far.

> What I've found is that when the article has an element query, placing it inside another component that also has an element query, you have to use pixels as the relative units don't seem to work.

I'm curious why the desire to base nested multiple elements with em-based repsonsive queries, it seems harder to think in ems than pixels for stuff like this, no? What's the advantage to using `em`?

We did try to support every unit, even the weird ones. That's strange and I'll keep investigating this.

I've built another demo from scratch in which I place `article` elements with a bunch of `@element` queries on them based on `em` units are placed within a larger layout still based on `@element` queries using `em` units ☛ http://codepen.io/tomhodgins/pen/beeQON

Does this solve the issue?

![codepen-smaller-80](https://cloud.githubusercontent.com/assets/955601/16139629/6a26f9ec-3417-11e6-8ac4-ef54d73e4078.gif)

**Comment by dropddesigns** [comment] 2016-06-20 23:08
Thank you for providing all of those examples. On initial inspection, it looks like you are getting results for the same thing that I am trying to achieve.

I can see you have main and aside sitting side by side and then stacking and these are styled based on the body using ems.

Okay... so as I was typing this up, I kept switching between your demos and my code and wondering why mine was breaking. The problem seems so obvious, I'm surprised neither of us picked this up before.

My demo works when you replace 600px with 37em but if you use 37.5em it breaks.

So perhaps the logic in the Javascript needs whole numbers?

I typically use up to 3 decimal places for my % and ems when doing responsive design so I can see this causing issues somewhere along the lines.

**Comment by tomhodgins** [comment] 2016-06-20 23:11
Thanks for helping uncover this bug! :) I wonder if it's as simple as adjusting a regex in the plugin that grabs the number. I'll see what we can do to get this working for you, it sounds like it should just need a small tweak in the right place.

**Comment by tomhodgins** [comment] 2016-06-21 02:30
@dropddesigns I might have figured it out - right around [Line 131 of the EQCSS source code](https://github.com/eqcss/eqcss/blob/gh-pages/EQCSS.js#L131) there are 2 regular expressions that extract the value and unit from any responsive query the plugin finds. Right now it seems to look for one or more digits, I want to change that to either one or more digits, or one or more digits followed by a period followed by one or more digits.

The way I've written it, I don't think it would accept things like `.5` without a digit before the '.' though, so before I commit this I'll ask the programmer and properly test it - but it looks like the problem is mostly figured out :)

Before:

```
unit = value.replace(/^\d+(\D+)$/, "$1");
value = value.replace(/^(\d+)\D+$/, "$1");
```

After:

```
unit = value.replace(/^(\d+|\d+\.\d+)(\D+)$/, "$2");
value = value.replace(/^(\d+|\d+\.\d+)\D+$/, "$1");
```

**Comment by tomhodgins** [comment] 2016-06-27 23:24
We've just pushed a [new release](https://github.com/eqcss/eqcss/releases/tag/v1.2.1), EQCSS 1.2.1 that adds support for numbers with decimals! This should be all fixed now :D

**Closed as completed by tomhodgins** 2016-06-27 23:24 UTC
